//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masks4ThePeople.Common.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Masks4ThePeopleEntities : DbContext
    {
        public Masks4ThePeopleEntities()
            : base("name=Masks4ThePeopleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Mask> Masks { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderProvider> OrderProviders { get; set; }
        public virtual DbSet<Printer> Printers { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
    }
}
