//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masks4ThePeople.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mask()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public System.Guid MaskId { get; set; }
        public Nullable<System.DateTime> PrintedOn { get; set; }
        public Nullable<byte> PrinterId { get; set; }
        public byte ColorId { get; set; }
        public byte SizeId { get; set; }
        public Nullable<System.DateTime> SoldOn { get; set; }
        public Nullable<System.DateTime> StrapsAddedOn { get; set; }
        public Nullable<System.DateTime> PaddingAddedOn { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Printer Printer { get; set; }
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
