//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masks4ThePeople.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Masks = new HashSet<Mask>();
        }
    
        public System.Guid OrderId { get; set; }
        public byte OrderProviderId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
        public Nullable<System.DateTime> EmailedOn { get; set; }
        public Nullable<System.DateTime> ShippedOn { get; set; }
        public Nullable<System.DateTime> FeedbackLeftOn { get; set; }
        public decimal Amount { get; set; }
    
        public virtual OrderProvider OrderProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mask> Masks { get; set; }
    }
}
